In [37]:
from Deep_Library_BCI import MultiTaskModel

mymo = MultiTaskModel(input_shape=(128,1), use_classifier=True, use_decoder=True)

2026-01-20 14:30:19.818993: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-20 14:30:19.883290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-20 14:30:21.336172: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1768915821.923275  578751 gpu_device.cc:2020] Created device /job:lo

8 128


In [7]:
mymo.encoder.summary()

Model: "encoder"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ encoder_input (InputLayer)      │ (None, 128, 1)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 128, 16)        │            64 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 128, 16)        │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 128, 16)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 64, 16)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64, 16)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 64, 64)         │         3,136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 64, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_5 (Activation)       │ (None, 64, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 32, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 32, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_6 (Conv1D)               │ (None, 32, 256)        │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 32, 256)        │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_6 (Activation)       │ (None, 32, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_6 (MaxPooling1D)  │ (None, 16, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 16, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_7 (Conv1D)               │ (None, 16, 128)        │        98,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 16, 128)        │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_7 (Activation)       │ (None, 16, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_7 (MaxPooling1D)  │ (None, 8, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │        32,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ latent (Dense)                  │ (None, 16)             │           52

 Total params: 186,224 (727.44 KB)

 Trainable params: 185,296 (723.81 KB)

 Non-trainable params: 928 (3.62 KB)

In [5]:
mymo.decoder.summary()

Model: "decoder"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ decoder_input (InputLayer)      │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1024)           │        17,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 8, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling1d (UpSampling1D)    │ (None, 16, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_8 (Conv1D)               │ (None, 16, 128)        │        49,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_8 (Activation)       │ (None, 16, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling1d_1 (UpSampling1D)  │ (None, 32, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_9 (Conv1D)               │ (None, 32, 256)        │        98,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_9 (Activation)       │ (None, 32, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling1d_2 (UpSampling1D)  │ (None, 64, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_10 (Conv1D)              │ (None, 64, 64)         │        49,216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_10 (Activation)      │ (None, 64, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ up_sampling1d_3 (UpSampling1D)  │ (None, 128, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 128, 16)        │         3,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_11 (Activation)      │ (None, 128, 16)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reconstruction (Conv1D)         │ (None, 128, 1)         │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 217,601 (850.00 KB)

 Trainable params: 217,601 (850.00 KB)

 Non-trainable params: 0 (0.00 B)

# CFM network

In [8]:


import keras

from keras import layers
CFM = keras.models.Sequential([
    layers.Conv1D(32, 5, input_shape=(160, 1), activation="relu", padding="same"),
    layers.Dropout(0.5),
    layers.Conv1D(64, 4, activation="relu"),
    layers.MaxPooling1D(2),
    layers.Conv1D(128, 3, activation="relu"),
    layers.MaxPooling1D(2),
    layers.Conv1D(256, 5, activation="relu", padding="same"),
    layers.Dropout(0.5),
    layers.Conv1D(128, 3, activation="relu"),
    layers.MaxPooling1D(2),
    layers.Flatten(),
    layers.Dense(50, activation="softsign"),
    layers.Dense(1, activation="sigmoid")
])

/home/silvia/Documents/GitHub/BCI_Project/.venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
CFM.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_17 (Conv1D)              │ (None, 160, 32)        │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 160, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_18 (Conv1D)              │ (None, 157, 64)        │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_15 (MaxPooling1D) │ (None, 78, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_19 (Conv1D)              │ (None, 76, 128)        │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_16 (MaxPooling1D) │ (None, 38, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_20 (Conv1D)              │ (None, 38, 256)        │       164,096 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 38, 256)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_21 (Conv1D)              │ (None, 36, 128)        │        98,432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_17 (MaxPooling1D) │ (None, 18, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 50)             │       115,250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 410,981 (1.57 MB)

 Trainable params: 410,981 (1.57 MB)

 Non-trainable params: 0 (0.00 B)

# In Utils

In [11]:
sampling_hz = 250
start = 3           # seconds where to start to extract windows
start = start*sampling_hz
input_shape = 128
shift = 62          # points to shift for next window in data
num_windows = 11    # how many windows to extract from each trial

end = start + (num_windows-1)*shift + input_shape
start, 6*250, end, 62*10+128+start

(750, 1500, 1498, 1498)

## Function extract window check

In [12]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

def extract_windows(x, win_len, shift):
    # x shape: (192, 68, 1024)
    windows = sliding_window_view(x, window_shape=win_len, axis=-1)
    # windows shape: (192, 68, 1024 - win_len + 1, win_len)

    # apply hop/shift
    windows = windows[..., ::shift, :]

    return windows


x = np.random.rand(192, 68, 748)
win_len = 128 
shift = 62
windows = extract_windows(x, win_len, shift)
windows.shape

(192, 68, 11, 128)

In [ ]:
x = np.array([[ 2*i+1 for i in range(4)],[ 2*i+2 for i in range(4)]])
x = x[np.newaxis, :, :]
x = np.concatenate((x, x*10), axis=0)
x, x.shape

(array([[[ 1,  3,  5,  7],
         [ 2,  4,  6,  8]],
 
        [[10, 30, 50, 70],
         [20, 40, 60, 80]]]),
 (2, 2, 4))

In [65]:
winded = extract_windows(x, win_len=2, shift=1)
winded, winded.shape

(array([[[[ 1,  3],
          [ 3,  5],
          [ 5,  7]],
 
         [[ 2,  4],
          [ 4,  6],
          [ 6,  8]]],
 
 
        [[[10, 30],
          [30, 50],
          [50, 70]],
 
         [[20, 40],
          [40, 60],
          [60, 80]]]]),
 (2, 2, 3, 2))

In [30]:
winded.reshape(-1, winded.shape[-1])

array([[ 1,  3],
       [ 3,  5],
       [ 5,  7],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [10, 30],
       [30, 50],
       [50, 70],
       [20, 40],
       [40, 60],
       [60, 80]])

## Verify with y - split things in the correct order - label, vs ROIs

### Function to split in train test val BEFORE windowing + function to create labels

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
## inputs x,y,
train_percentage = 0.7 ;        trp=train_percentage
validation_percentage = 0.15;   vp=validation_percentage
test_percentage = 0.15;         tep = test_percentage

################## TODO ######################
# function create labels y (so i can clearly see that it is a passage)

# assegno positivi a quelli di dopo (MI) e negativi a quelli di prima (Rest)
y = np.ones((192, 68))
y[0:96, :] = -1

# assegno valore in base a ROI, da ±1 a ±68
for col in range(y.shape[1]):
    y[:, col] *= (col+1)

y = y.reshape(-1,) # da eseguire insieme al reshape dei dati
y

x = np.random.rand(192, 68, 748)

#windows = extract_windows(x, win_len, shift)
x.shape

x = x.reshape(-1,x.shape[-1],)
x.shape, y.shape

if trp + vp + tep != 1:
    raise ValueError("Train, validation, and test percentages must sum to 1.")


X_train, X_tmp, y_train, y_tmp = train_test_split(
    x, y,
    test_size=1-trp,          # 70% train, 30% temp
    stratify=y,             # preserves label balance
    random_state=42,
    shuffle=True
)


X_val, X_test, y_val, y_test = train_test_split(
    X_tmp, y_tmp,
    test_size=vp/(vp+tep),          # 15% val, 15% test
    stratify=y_tmp,         # preserves balance again
    random_state=42,
    shuffle=True
)


((13056, 748), (13056,))

In [ ]:
1/68/2*100

0.7352941176470588

In [ ]:
for i in set(y_val):
    print(i,"\t", sum(y_val==i)/len(y_val)*100, sum(y_val==i))

1.0 	 0.7150153217568949 14
2.0 	 0.7150153217568949 14
3.0 	 0.7660878447395302 15
4.0 	 0.7150153217568949 14
5.0 	 0.7150153217568949 14
6.0 	 0.7150153217568949 14
7.0 	 0.7150153217568949 14
8.0 	 0.7660878447395302 15
9.0 	 0.7660878447395302 15
10.0 	 0.7660878447395302 15
11.0 	 0.7150153217568949 14
12.0 	 0.7150153217568949 14
13.0 	 0.7660878447395302 15
14.0 	 0.7150153217568949 14
15.0 	 0.7150153217568949 14
16.0 	 0.7150153217568949 14
17.0 	 0.7150153217568949 14
18.0 	 0.7660878447395302 15
19.0 	 0.7660878447395302 15
20.0 	 0.7660878447395302 15
21.0 	 0.7150153217568949 14
22.0 	 0.7660878447395302 15
23.0 	 0.7660878447395302 15
24.0 	 0.7150153217568949 14
25.0 	 0.7660878447395302 15
26.0 	 0.7150153217568949 14
27.0 	 0.7660878447395302 15
28.0 	 0.7660878447395302 15
29.0 	 0.7660878447395302 15
30.0 	 0.7150153217568949 14
31.0 	 0.7150153217568949 14
32.0 	 0.7660878447395302 15
33.0 	 0.7150153217568949 14
34.0 	 0.7660878447395302 15
35.0 	 0.76608784473953

### Function that take x, y. split x in many windows and then proliferate "y" in order to match X

In [ ]:
def extract_windows(x, win_len=128, shift=62):
    """ OK, verified (see Test.ipynb -> Function extract window check)"""
    # x shape: (192, 68, 748) 
    # 192 trials, 68 ROIs, 748 time points
    # 128 + 62*(11-1)  = 748

    windows = sliding_window_view(x, window_shape=win_len, axis=-1)
    # windows shape: (192, 68, 748 - win_len + 1, win_len)

    # apply hop/shift
    windows = windows[..., ::shift, :]

    return windows

win_len = 128 
shift = 62

In [81]:
X = X_test
Y = y_test

In [ ]:
X_windowed = extract_windows(X)
Y_windowed = np.repeat(Y[:, None], X_windowed.shape[1], axis=1)
X_windowed.shape, Y_windowed.shape

((1959, 11, 128), (1959, 11))

In [88]:
X_windowed_reshaped = X_windowed.reshape(-1, X_windowed.shape[-1])
Y_windowed_reshaped = Y_windowed.reshape(-1,)
X_windowed_reshaped.shape, Y_windowed_reshaped.shape

((21549, 128), (21549,))

In [93]:
for qua in Y_windowed_reshaped:
    print(qua)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-20.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-65.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
-4.0
17.0
17.0
17.0
17.0
17.0
17.0
17.0
17.0
17.0
17.0
17.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
-53.0
66.0
66.0
66.0
66.0
66.0
66.0
66.0
66.0
66.0
66.0
66.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
36.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-34.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
-28.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
20.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-46.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
-21.0
26.0
26.0
26.0
26.0
26.0
26.0
26.0
26.0
26.0
26.0
26.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-48.0
-35.0
-35.0
-35.0
-35.0
-35.0
-35.0
-35.0
-

### All togheder

In [1]:
import numpy as np
from Utils import windowize, split_train_val_test
x = np.ones((192,68,748))

train,val,test = split_train_val_test(x, train_percentage=0.7, validation_percentage=0.15, test_percentage=0.15)

In [ ]:
train

(array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]], shape=(9139, 748)),
 array([ 40.,  30., -37., ...,  58., -10.,  18.], shape=(9139,)))

In [3]:
9139*11

100529

In [ ]:
x_train, y_train = windowize(*train)

(array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]], shape=(100529, 128)),
 array([40., 40., 40., ..., 18., 18., 18.], shape=(100529,)))