In [2]:
Interesting_regions =   [4, 5, 32, 33, 44, 45, 48, 49]
Interesting_right =   [5, 33, 45, 49]
Interesting_left =   [4, 32, 44, 48]

Good_subjects =         [0, 2, 5, 9, 12, 14]
Ok_subjects =           [1, 3, 4, 6, 11, 13, 19]
Other_subjects = [i for i in range(20) if i not in Ok_subjects and i not in Good_subjects]

Subjects_dict = {"Good_subjects": Good_subjects, "Ok_subjects":Ok_subjects, "Other_subjects":Other_subjects}

data_folder="/Users/giovanni.messuti/Desktop/BCI_Project/Data/"

freq_personalized = {"subject_0":[9,14.5],
                     "subject_1":[8,12],
                     "subject_2":[8,13.5],
                     "subject_3":[4,9.5],
                     "subject_4":[18,23.5],
                     "subject_5":[4,9.5],
                     "subject_6":[4,9.5],
                     "subject_7":[4,9.5],
                     "subject_8":[4,12],
                     "subject_9":[9.5,15.5],
                     "subject_10":[9,14.5],
                     "subject_11":[4,10.5],
                     "subject_12":[8,13.5],
                     "subject_13":[4,10.],
                     "subject_14":[12,18],
                     "subject_15":[4,8],
                     "subject_16":[4,13],
                     "subject_17":[4,12],
                     "subject_18":[4,9.5],
                     "subject_19":[4,12.5],
}

from BCI_Library import read_subject, plot_brain, train_models, extract_features_more_bands, saveresults_pickle, select_rows, compute_welch_select_regions, extract_features_from_spectra_more_bands


In [3]:

subject_index = 15

data_2_MI = read_subject(data_folder, "EEG", "MI",subject_index)
data_2_Rest = read_subject(data_folder, "EEG", "Baseline",subject_index)

# My frequency sampling
sfreq = 250

In [4]:
WMI, WRe, FreqMI, regions = compute_welch_select_regions(data_2_MI, data_2_Rest,sfreq,important_regions=[])

Effective window size : 1.200 (s)
Effective window size : 1.200 (s)


In [5]:
regions

[29, 37, 53, 11, 54, 55, 10, 65]

In [7]:

tuple(compute_welch_select_regions(wpsdMI=WMI, wpsdRest=WRe, frequiMI=FreqMI, important_regions=[], nbest_regions=427))

(29,
 37,
 53,
 11,
 54,
 55,
 10,
 65,
 39,
 61,
 36,
 41,
 57,
 34,
 67,
 52,
 35,
 19,
 45,
 4,
 49,
 9,
 44,
 60,
 62,
 31,
 33,
 32,
 48,
 46,
 56,
 17,
 66,
 47,
 51,
 0,
 18,
 24,
 63,
 23,
 22,
 7,
 30,
 16,
 27,
 50,
 64,
 59,
 21,
 15,
 2,
 8,
 5,
 12,
 13,
 1,
 14,
 38,
 20,
 3,
 6,
 26,
 40,
 43,
 58,
 42,
 28,
 25)

# jfjff

In [ ]:
import numpy as np
datini = [i for i in range(20)]  + [(i+1)*100 for i in range(20)] 
labels = [1 for i in range(20)]  + [0 for i in range(20)] 
from sklearn.model_selection import StratifiedKFold 
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=224)
#for fold_idx, (train_idx, val_idx) in enumerate(kf.split(datini)):
datini = np.array(datini)





In [20]:
for fold_idx, (train_idx, val_idx) in enumerate(kf.split([0 for i in range(40)], labels)):
    print(datini[val_idx])

[   0    4   11   14  200  500  900 1900]
[   1    6   13   19  100  800 1300 1600]
[   3    5    8   10  300  400  600 1500]
[   9   15   17   18 1100 1400 1700 2000]
[   2    7   12   16  700 1000 1200 1800]


In [ ]:
from sklearn.model_selection import StratifiedKFold 
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=224)
for fold_idx, (train_idx, val_idx) in enumerate(kf.split([0 for i in range(40)], labels)):
    2